### ISSUE TITLE
writetape_close flushtape double free

### ISSUE THREAD

**Issue by Safari77** [Tarsnap/tarsnap#100]
```writetape_close```: in flushtape, if chunklist_exportdup returns true, ```d->h.index``` is freed and flushtape returns -1 , after ```err2``` it does ```stream_free(&d->h)``` which is ```chunklist_free(S->index)```

**Comment by gperciva** [comment]
I can confirm this behaviour; easiest way to test is to make line 768 of `tar/multitape/multitape_write.c` into `goto err2;`

I am working on a fix and investigating potential related issues now.

**Comment by gperciva** [comment]
Setting `d->*.index` to NULL after freeing them avoids the double-free, but it leaves some memory leaks.

BTW, thank you for this report!  (sorry for forgetting to add this to the previous comment)

**Comment by cperciva** [comment]
I'm pretty sure the free() calls in the error-handling path of flushtape should be `free(tmi.Xindex);` for X = 't', 'c', 'h'.  Graham, since you presumably have valgrind set up to confirm this bug, can you see if that change fixes it?

**Comment by gperciva** [comment]
That was the conclusion I reached, and I verified the fix easily with regular archives, but I had some issues tested it with checkpoints.  I've resolved those, and it works there too.  PR #101

**Comment by cperciva** [comment]
Thanks, committed.  @Safari77, do you have a Tarsnap account?  This is worth a $20 bug bounty.
