### ISSUE TITLE
tarsnap.com is accessible over non-https

### ISSUE THREAD

**Issue by zachborboa** [Tarsnap/tarsnap#106]
First search result also points to non-https version of site
https://www.google.com/search?q=tarsnap

Maybe change 
`<link rel="canonical" href="http://www.tarsnap.com/">`
to
`<link rel="canonical" href="https://www.tarsnap.com/">`

**Comment by cperciva** [comment]
This is deliberate.  I plan on pushing people towards the HTTPS side in the future, but right now I take advantage of the HTTP/HTTPS separation in javascript's "same origin" policy to make sure that issues in the javascript on the main site don't allow unintended access to the account management section (which *is* forced to HTTPS).  Once I move that to a new domain I'll be able to keep everything on the HTTPS side.
