### ISSUE TITLE
Add --verify-config option

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/tarsnap#132]
Suggestion from a Tarsnap user:

> I’m a rather new but very happy user of tarsnap, and I have started pushing backups all over the place.  To do this I’m using a git tree that holds configuration both of tarsnap proper, and that of feather that I use to schedule backups.  In this context I would like to be able to run tarsnap with the single purpose of verifying the validity of the configuration file, so I can have tools prevent broken (well, syntactically broken) configuration files from being pushed to clients.  Something as simple as: tarsnap --verify-config

We won't want this to load tarsnap keys, since we might want to check a configuration file on a system without keys installed.  So the handling of the `--keyfile` option will need to change from "load the keys" to "store the path and load the keys later".  But that should be fairly straightforward, and I don't *think* there are any other similar issues.

Then we should be able to check this option and bail out after the configuration file(s) are processed.

**Comment by gperciva** [comment]
This was added in #134, and will be in 1.0.37.
