### ISSUE TITLE
 Unable to continue traversing directory tree

### ISSUE THREAD

**Issue by Vanhecke** [Tarsnap/tarsnap#162]
So this error started happening.

Example: 
```
a Path/Project/.git/objects/e1/411758c15f602e6521843f1a4ac6106013c525
a Path/Project/.git/objects/e1/4cbe24166294c4a78918718eacd4c1b1d9f4ea
a Path/Project/.git/objects/e1/b194523aefef40ebcaee43294fd269ddca31b4
a Path/Project/.git/objects/e0/02fa2ae53eec2a26379859f8102b6278614ad0
a Path/Project/.git/objects/e0/4d9dd1811d729196ededdcf7d10c4d99685161
a Path/Project/.git/objects/e0/e682ab9aecb251d53faf652c5d371f85bae133
tarsnap: Path/Project/.git/objects/df: Unable to continue traversing directory tree
```

It always stops on this folder. I haven't worked on this project/git repo for a long time and the last-changed time of the folder dates back to 2015, it has been tarsnapped many times since then.

**Comment by gperciva** [comment]
Hmm.  That error message appears to only occur if the libarchive code in `tar/tree.c` produces `TREE_ERROR_FATAL`, after a failure with `fchdir`, `chdir`, or `readdir`.

To help us narrow it down, could you send us the output of this:

```
cd Path/Project/
ls -ld .git/objects/df/
ls -ld .git/objects/
```

I don't think the libarchive code would produce such an error if it was as simple as having weird permissions on a directory, but let's check that anyway.

Also, does anything look unusual if you do

```
ls -l .git/objects/df/
```

**Comment by Vanhecke** [comment]
I received Disk I/O errors running those commands. 
I re-plugging the disk (its an sdcard), cleaned the slot and now everything is working again.
