### ISSUE TITLE
humanize-numbers doesn't affect SIGINFO output

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap#164]
The `siginfo_printinfo()` function in `tar/siginfo.c` should obey the `--humanize-numbers` command.

**Comment by gperciva** [comment]
Arises from: http://mail.tarsnap.com/tarsnap-users/msg01264.html

**Comment by marrie** [comment]
I hope this can be looked into as not all of us want to convert the bite count. I suck at doing that on the fly.. Thanks for looking into this.

**Comment by gperciva** [comment]
Fixed in #166.
