### ISSUE TITLE
index of vulnerability

### ISSUE THREAD

**Issue by abhi7918** [Tarsnap/tarsnap#180]
https://www.tarsnap.com/images/
https://www.tarsnap.com/download/

by this vulnerability grab any files directly 
and should not be accessible by an unauthorized party who happens to know the URL. Nevertheless, directory listings can aid an attacker by enabling them to quickly identify the resources at a given path, and proceed directly to analyzing and attacking them.
Configure your web server to prevent directory listings for all paths beneath the web root;
Place into each directory a default file (such as index.htm) which the web server will display instead of returning a directory listing.

**Comment by cperciva** [comment]
Not a vulnerability.  Not even a bug.
