### ISSUE TITLE
./configure fails on Ubuntu

### ISSUE THREAD

**Issue by mulle-nat** [Tarsnap/tarsnap#206]
The INSTALL documentation (lol which ?) should say that you need

`apt-get install e2fslibs-dev zlib1g-dev libssl-dev`

otherwise you may get (or some such)

```
checking for ext2fs/ext2_fs.h... no
configure: error: *** ext2fs/ext2_fs.h missing ***
```

**Comment by gperciva** [comment]
Hi, thanks for the report.  The "compiling" webpage already explicitly mention `e2fslibs-dev`:

> Debian, Ubuntu, and related Linux distributions:
>
>     sudo apt-get install gcc libc6-dev make libssl-dev zlib1g-dev e2fslibs-dev
>
> https://www.tarsnap.com/compiling.html

However, it is true that this information is not included in the tarball.  I'll take a look at adding it somewhere.

**Comment by mulle-nat** [comment]
```
echo "Read [compiling](https://www.tarsnap.com/compiling.html) if you have problems running `./configure` " > INSTALL 
```

would have helped me, as the information about "compiling" had already scrolled by. Admittedly I could have put in more effort to find it though :)

**Comment by gperciva** [comment]
We've now added a top-level `BUILDING` file (also pointed to from the `README.md`) that lists dependencies, and sample `apt-get` and `yum` commands to install them.
