### ISSUE TITLE
Add --passphrase-force option

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/tarsnap#207]
This option would circumvent the "will this require too much memory / time" mechanism in scryptenc and just assume that the user knows what they're doing.  Probably worth adding the same option to scrypt too...

**Comment by gperciva** [comment]
Err, that sounds like you want to brute-force things.  Maybe for those dangerous ASICs.  ;)

How about `--passphrase-mem-force` instead?

**Comment by gperciva** [comment]
ah, I didn't notice the "/ time" part, since I was thinking of the mailing list thread.  How about `passphrase-resources-force`, then?

**Comment by cperciva** [comment]
`--passphrase-resources-force` seems a bit verbose.  And "force" is pretty typical UNIXese for "do what I told you to do even if you think it's a bad idea".
