### ISSUE TITLE
Support write-only key existing on a separate node as part of a shared dataset

### ISSUE THREAD

**Issue by Intensity** [Tarsnap/tarsnap#242]
Initially I had thought I could generate a key for a single, shared dataset, and then derive a write-only key that I put on other satellite hosts. The goal was to let the satellite hosts write new archives, and let read operations happen only on the original main host (the one that has the original key).

After trying this out with `tarsnap-keymgmt` with the `-w` option (I placed the resultant "write-only" key on the remote hosts), I found that on the satellite hosts, after just one or two operations, further create archive calls will fail. `tarsnap` at that point believes that it needs to run a `--fsck`, but those write-only nodes cannot do so since they don't have read permission. It's my understanding that this isn't possible due to a requirement of keeping the cache directory in sync. I'm still not able to make it happen even if I delete the cache directory, run the `--fsck` on the original node, and even if I manually erase all archives for the dataset prior to a satellite write.

I'm wondering if there's a way to enable the use case I have in mind, and if there is anything intrinsically in the way of making this possible.

**Comment by gperciva** [comment]
There are two possible ways of running Tarsnap on multiple machines with the same key: http://www.tarsnap.com/multiple-machines.html

The important point is not that each cachedir needs to be in sync with other cachedirs; rather, the cachedir needs to be in sync with the *Tarsnap server*.  Look at it this way: the satellite host needs to know which data is already on the server before it can determine what bytes to upload!

**Comment by gperciva** [comment]
Our page about running Tarsnap on multiple machines with the same key has been updated to clarify this situation: http://www.tarsnap.com/multiple-machines.html
Please let me know if the rewrite isn't clear.
