### ISSUE TITLE
potential commits for 1.0.36 release notes

### ISSUE THREAD

**Issue by gperciva** [Tarsnap/tarsnap#27]
I'm not suggesting you need to include git hashes; these are just so that you can look up the commit quickly if you need to refresh your memory

- fix misc memory leaks given unusual failure conditions (edfd943133dfc040e1df48d588df5ce89dcf5ae0, 0df0b6f0eda04801f1c9a47aa243dfdc3ca48464)

- warn if user attempts to place options at the end of the command line (c3c383ecdc6aee6bbfae05b0b2c69886ce600b59)

- on 32-bit and smaller machines, an attacker who can store a validly HMACed tarsnap block can make tarsnap crash upon listing archives or reading an archive the attacker created; on larger machines, that attacker can make tarsnap waste a lot of memory.  (77751c1406dcc95c60b0651ba8da9b0e621dfb58)

- add AESNI support (45efe0c7c0ffaab20706585d357b4336657e25cc)

- add better attempt at zeroing a buffer "insecure_memzero" (a847930f75fb5f6b810cf858428f7b76008d012f)

- add --retry-forever (c5d4a514ad0b2ebc03a9aa5bb813e8547a6b18dd)

- Support listing archives with files >68 years old (ebd4ece9cbd9ea1ca7680988e783e46ad9a5eb36)
  [probably not an important issue, but it would be funny to see that in the release notes!]

- fix for builds containing whitespace, and out-of-source-tree builds (a19cdf393f43d69c2f77524763cecf9eea0557e6, and later commits)

- add SSE2 support (527e7a8bf04a8b118f1662a585acd3e95c009d93)

- add tarsnap bash completion (49eeddec8bf7f32ee243f2f1238bea279fa1ffb9)

- allow uses to test dedupe&encryption without signing up (--dry-run compression without a keyfile 92d5c36d72de999836d124f9983c8643e6123aa3)

- disable --aggressive-networking if --maxbw-rate-* (9478f362fa506e2bc1bb336b790470b453b64b11)

- add --creationtime (da68672501193c43a894db878fcfb874190841a7)

**Comment by cperciva** [comment]
I think I managed to list everything important in the email I just sent to the alphatest list.
