### ISSUE TITLE
Tarsnap web site mentions Windows Subsystem for Linux as beta

### ISSUE THREAD

**Issue by chamalsl** [Tarsnap/tarsnap#304]
Tarsnap web site mentions Windows Subsystem for Linux as beta in below mentioned URLs.
1. https://www.tarsnap.com/download.html#windows
2. https://www.tarsnap.com/gettingstarted.html 

Word "beta" should be removed since Windows Subsystem for Linux is no longer in beta.

**Comment by gperciva** [comment]
Thanks for the report!  Yes, this change is coming.  Also, the WSL download info will mention the SUSE and openSUSE userland as well as Ubuntu (https://blogs.msdn.microsoft.com/commandline/2017/07/19/suses-linux-distros-for-wsl-now-available-in-the-windows-store/).

**Comment by gperciva** [comment]
Fixed
