### ISSUE TITLE
zero exit code when tarsnap fails due to negative balance

### ISSUE THREAD

**Issue by pushcx** [Tarsnap/tarsnap#328]
```
$ tarsnap --configfile tarsnap.conf --list-archives
tarsnap: Cannot read list of archive fragments: Account balance is not positive.
tarsnap: Please add more money to your tarsnap account
tarsnap: Error listing archives
tarsnap: Error exit delayed from previous errors.
$ echo $?
0
```

I deliberately let the account balance run to negative because I wanted to see our [backup cron job fail](https://github.com/lobsters/lobsters-ansible/issues/36), and it didn't fail because tarsnap exited with a 0 code indicating success.

Could tarsnap please report the error condition with a non-zero exit code? Thanks!

**Comment by gperciva** [comment]
What version and OS are you using?  I'm having difficulty reproducing this.

**Comment by gperciva** [comment]
Is it possible that your `tarsnap` is a wrapper shell script?  Please run:
```
$ which tarsnap
$ tarsnap --version
```

I'm really puzzled by this. If you see "Error exit delayed", then you're at the end of `int main()` in `bsdtar.c`:
```
	if (bsdtar->return_value != 0)
		bsdtar_warnc(bsdtar, 0,
		    "Error exit delayed from previous errors.");
	return (bsdtar->return_value);
}
```
https://github.com/Tarsnap/tarsnap/blob/master/tar/bsdtar.c#L1194
(and those lines haven't been changed since 41f175d, which is tarsnap 1.0.0!

My understanding is that `int main()` will be returning the non-zero `bsdtar->return_value`.  So either that value is somehow changing while printing the warning, or the executable is failing to use the return value of `int main()` in the exit code, or something else is intercepting the real error code and giving you something else on your shell.

**Comment by pushcx** [comment]
Sorry, I should've thought to include this in the intial report. We're running Ubuntu 16.04.5 LTS. Our `tarsnap --version` reports `tarsnap 1.0.39`, `which tarsnap` points to `/usr/bin/tarsnap`, and it was installed from `http://pkg.tarsnap.com/deb/xenial". You can see [our script here](https://github.com/lobsters/lobsters-ansible/blob/master/roles/tarsnap/files/backup-cron) and the other related config is in that `roles/tarsnap` tree, if any of it helps.

I'm glad this wasn't intended behavior, seeing a failure and 0 was quite a surprise to me. :)

**Comment by gperciva** [comment]
I must admit that I'm still completely baffled.  Theoretically, if `bsdtar->return_value` is 256, it could result in the behaviour you see.  But if you see "`Error listing archives`" then the very next line is `bsdtar->return_value = 1;`
https://github.com/Tarsnap/tarsnap/blob/master/tar/glue/tape.c#L196
and then it returns to `int main()` and very soon reaches the end.

Sorry to ask this, but could you run:
```
$ /usr/bin/tarsnap --configfile tarsnap.conf --list-archives ; echo $?
```

all on one line and send me the result?

**Comment by pushcx** [comment]
So, I have to tweak this command to include the full path `/etc/tasrnap.conf`, but the output is:

```
tarsnap: The read authorization key is required for --list-archives but is not available
1
```

This is a production app server. As part of worst-case-scenario planning, I only gave it the write key so that an attacker who takes over the box can't wipe the backups.

**Comment by gperciva** [comment]
Thanks for running the command!  It looks like the error message is good, and it produces a non-zero exit code.  So I think this issue can be closed.  If you have more info, please don't hesitate to write again.

**Comment by pushcx** [comment]
I think it's succeeding because I funded the account, not because an underlying issue was addressed. As nothing else has changed, what will prevent it from failing with a zero exit code in a few months when the balance runs down again?

**Comment by gperciva** [comment]
I thought of something else to try, which I can do tomorrow.

**Comment by pushcx** [comment]
That's really strange. I've checked my `history` and see `/usr/bin/tarsnap --configfile tarsnap.conf --list-archives ; echo $?` as a single line. But what's odd is that I *don't* see myself running `cd /etc` first; I can only be in `/root` after the `sudo`. There is no copy of `tarsnap.conf` in `/root`; a `find` confirms that the only copy of the file is `/etc/tarsnap.conf`. When I run that now, I get the perfectly clear error `tarsnap: Cannot read config file: no-such-file: No such file or directory` and exit code 1.

So it seems almost certain there's user error at work, though I'm baffled as to what I could've done to produce this output given that my shell history implies I should've gotten an entirely different error. Let's not take up more of your time here. let's go ahead and close it, and I'll let the balance run down again and report back what happens when I test then. Should be a little under 150 days given the current, stable usage. I've marked my calendar to start watching for it.

**Comment by pushcx** [comment]
It ran down to negative again and I can't reproduce the reported behavior. I tried all the invocations of tarsnap mentioned above and a few more, and I always got exit code 1. Still scratching my head *what* I did, but now pretty high confidence this was just some kind of user error. Thanks again for looking into this with me.
