### ISSUE TITLE
storage_write_start does dry runs a bit weirdly

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/tarsnap#34]
We should probably change the `storage_write_start` API from "If ${dryrun} is nonzero, perform a dry run (which ignores ${lastseq} and sets ${seqnum} to 32 0s)." to "If ${dryrun} is nonzero, ignore ${lastseq} and ${seqnum}".  Or possibly push dryrun resolution higher in the stack even -- don't create a storage cookie at all, but instead just have the multitape and chunks layers be aware of dryruns and not issue calls to the storage layer?

But storage_write_start is doing a silly amount of pointless initialization given that a dry-run storage cookie should never do anything.  There's got to be a better way to organize this code.

**Comment by gperciva** [comment]
Addressed in #61.
