### ISSUE TITLE
Clarification around redistribution terms

### ISSUE THREAD

**Issue by jcs** [Tarsnap/tarsnap#351]
I realize the license can't be changed to a completely free one (#66) but can the redistribution terms be modified to make it easier to distribute unmodified binary packages?

> Redistribution and use in source and binary forms, without modification, is permitted for the sole purpose of using the "tarsnap" backup service provided by Tarsnap Backup Inc.

That means (or at least could be interpreted) that any distribution of a compiled binary, even built from unmodified source code, has to be done with the sole purpose of using the Tarsnap service.  A project like OpenBSD (or any descendent fork) wishing to distribute precompiled binaries from unmodified source code can't make such guarantees.

Can the restriction of "for the sole purpose of using the "tarsnap" backup service provided by Tarsnap Backup Inc." be put only on the use and the redistribution just be "without modification"?

So something like:

> Redistribution in source and binary forms, without modification, is permitted.  Use in source or binary forms, without modification, is permitted for the sole purpose of using the "tarsnap" backup service provided by Tarsnap Backup Inc.

**Comment by cperciva** [comment]
I'm not entirely sure I see the problem.  I'd assume that OpenBSD would like to distribute Tarsnap packages so that people can use Tarsnap, and the motives that someone might have in downloading the packages are irrelevant to whether OpenBSD can distribute them.

**Comment by gperciva** [comment]
> the motives that someone might have in downloading the packages are irrelevant to whether OpenBSD can distribute them.

One could argue that the "motives" are precisely what makes the client legal to distribute (or not).  I mean, if I download the source code for the purpose of grepping for swear words, that's technically not supported the license.  But who's liable for that?  The downloader, server, or both?

I agree that it would be silly for OpenBSD to require users to send a signed affidavit, certifying that their sole purpose of getting a copy of tarsnap is to use it with Tarsnap Backup Inc., before they would allow somebody to download the tarball.  But is there solid legal basis in saying "here's a web server that sends you a tarball if you issue a `GET` request.  But don't send that `GET` unless you're going to use it with Tarsnap Backup Inc."?

**Comment by jcs** [comment]
>  But who's liable for that? The downloader, server, or both?

Probably the person that put it on the server (and perhaps everyone that runs a server that mirrored from that person) because they made it available for redistribution whether or not anyone actually downloads it.  But I can't say for certain, and it's not clear from the license text, so that's what we have to go by to determine whether we (and anyone else that builds packages from OpenBSD's ports tree) can redistribute a binary package.  Terms on usage don't matter to us because the package builders and distributors are not going to be using it.

If it matters, I am not asking for this as an OpenBSD developer, but as a Tarsnap customer.  It's a pain to have to recompile your software from the OpenBSD port every release, especially for multiple machines that I backup to Tarsnap.

**Comment by etug80** [comment]
Tarsnap could be relicensed to [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)

**Comment by jcs** [comment]
I stopped using Tarsnap years ago, so I no longer care about this
