### ISSUE TITLE
bug bounty

### ISSUE THREAD

**Issue by login000** [Tarsnap/tarsnap#362]
Cosmetic error on the Tarsnap website:
On the page https://www.tarsnap.com/kivaloo.html, "thus there is no need to for separate periodic "compaction" to be performed" should say "thus there is no need for separate periodic "compaction" to be performed".

**Comment by gperciva** [comment]
Thanks!  If you haven't already done so, please send your email address to Colin so you can get account credit for this.

**Comment by login000** [comment]
@cperciva I'd like the account credit to be sent to Ben's (github.com/benharri) Tarsnap account. I don't know the email address they use with Tarsnap, though.

**Comment by login000** [comment]
I've found the right email address. the name of the mailbox is "ben", and the domain is at "tilde.team" (cc @cperciva). Should I have sent the email address via email?

**Comment by login000** [comment]
Another cosmetic error on the Tarsnap website:
On the page https://www.tarsnap.com/crypto.html, "A 256-bit HMAC-SHA256 key used to protect each individual block of data from tampering." should say "A 256-bit HMAC-SHA256 key is used to protect each individual block of data from tampering."
I would like the account credit to be sent to ben at tilde.team.

**Comment by gperciva** [comment]
I'd normally send an address by email, but it's fine.  A quick google search shows that the address is used in full in many places on the web, so it's not a spam risk for him.

**Comment by cperciva** [comment]
I've paid the $1 bounty.  @gperciva Can you please add this to the bug bounty table (as "anonymous", unless @login000 wants to give us a name)?

**Comment by login000** [comment]
Anonymous would be fine :)

>

**Comment by gperciva** [comment]
Thanks for the report.  Your bounty is accounted at the bottom of http://www.tarsnap.com/bounty-winners.html now.  :)
