### ISSUE TITLE
OS X - error: use of undeclared identifier 'CLOCK_REALTIME'

### ISSUE THREAD

**Issue by grahammiln** [Tarsnap/tarsnap#42]
Building tarsnap 1.0.36 with OS X 10.10.5 and Xcode tools 6.4, the build encounters an error.

The file `libcperciva/util/monoclock.c` appears to be calling `clock_gettime` which [may not exist on OS X](http://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x):

## make output

	$ make all install clean
	/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
	gcc -DHAVE_CONFIG_H -I.    -I./tar -I./libarchive -I./lib/crypto -I./lib/datastruct -I./lib/keyfile -I./lib/netpacket -I./lib/netproto -I./lib/network -I./lib/scryptenc -I./lib/util -I./libcperciva/alg -I./libcperciva/cpusupport -I./libcperciva/crypto -I./libcperciva/datastruct -I./libcperciva/events -I./libcperciva/network -I./libcperciva/util -I. -D CPUSUPPORT_CONFIG_FILE=\"cpusupport-config.h\" -DPOSIXFAIL_MSG_NOSIGNAL -g -O2 -MT libcperciva/util/lib_libtarsnap_a-monoclock.o -MD -MP -MF libcperciva/util/.deps/lib_libtarsnap_a-monoclock.Tpo -c -o libcperciva/util/lib_libtarsnap_a-monoclock.o `test -f 'libcperciva/util/monoclock.c' || echo './'`libcperciva/util/monoclock.c
	libcperciva/util/monoclock.c:32:6: warning: implicit declaration of function 'clock_gettime' is
		  invalid in C99 [-Wimplicit-function-declaration]
			if (clock_gettime(CLOCK_REALTIME, &tp) == 0) {
				^
	libcperciva/util/monoclock.c:32:20: error: use of undeclared identifier 'CLOCK_REALTIME'
			if (clock_gettime(CLOCK_REALTIME, &tp) == 0) {
							  ^
	1 warning and 1 error generated.
	make[1]: *** [libcperciva/util/lib_libtarsnap_a-monoclock.o] Error 1
	make: *** [all] Error 2

## compiler

	$ gcc -v
	Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
	Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
	Target: x86_64-apple-darwin14.5.0
	Thread model: posix

## configure output

	$ ./configure --prefix='/Volumes/Documents/tarsnap'
	checking build system type... x86_64-apple-darwin14.5.0
	checking host system type... x86_64-apple-darwin14.5.0
	checking target system type... x86_64-apple-darwin14.5.0
	checking for a BSD-compatible install... /usr/bin/install -c
	checking whether build environment is sane... yes
	checking for a thread-safe mkdir -p... config.aux/install-sh -c -d
	checking for gawk... no
	checking for mawk... no
	checking for nawk... no
	checking for awk... awk
	checking whether make sets $(MAKE)... yes
	checking whether make supports nested variables... yes
	checking for gcc... gcc
	checking whether the C compiler works... yes
	checking for C compiler default output file name... a.out
	checking for suffix of executables... 
	checking whether we are cross compiling... no
	checking for suffix of object files... o
	checking whether we are using the GNU C compiler... yes
	checking whether gcc accepts -g... yes
	checking for gcc option to accept ISO C89... none needed
	checking whether gcc understands -c and -o together... yes
	checking for style of include used by make... GNU
	checking dependency style of gcc... gcc3
	checking for ranlib... ranlib
	checking for strip... strip
	checking how to run the C preprocessor... gcc -E
	checking for grep that handles long lines and -e... /usr/bin/grep
	checking for egrep... /usr/bin/grep -E
	checking for ANSI C header files... yes
	checking for sys/types.h... yes
	checking for sys/stat.h... yes
	checking for stdlib.h... yes
	checking for string.h... yes
	checking for memory.h... yes
	checking for strings.h... yes
	checking for inttypes.h... yes
	checking for stdint.h... yes
	checking for unistd.h... yes
	checking minix/config.h usability... no
	checking minix/config.h presence... no
	checking for minix/config.h... no
	checking whether it is safe to define __EXTENSIONS__... yes
	checking whether to enable maintainer-specific portions of Makefiles... no
	checking for ANSI C header files... (cached) yes
	checking for dirent.h that defines DIR... yes
	checking for library containing opendir... none required
	checking for sys/wait.h that is POSIX.1 compatible... yes
	checking acl/libacl.h usability... no
	checking acl/libacl.h presence... no
	checking for acl/libacl.h... no
	checking attr/xattr.h usability... no
	checking attr/xattr.h presence... no
	checking for attr/xattr.h... no
	checking ctype.h usability... yes
	checking ctype.h presence... yes
	checking for ctype.h... yes
	checking err.h usability... yes
	checking err.h presence... yes
	checking for err.h... yes
	checking errno.h usability... yes
	checking errno.h presence... yes
	checking for errno.h... yes
	checking fcntl.h usability... yes
	checking fcntl.h presence... yes
	checking for fcntl.h... yes
	checking grp.h usability... yes
	checking grp.h presence... yes
	checking for grp.h... yes
	checking for inttypes.h... (cached) yes
	checking langinfo.h usability... yes
	checking langinfo.h presence... yes
	checking for langinfo.h... yes
	checking limits.h usability... yes
	checking limits.h presence... yes
	checking for limits.h... yes
	checking linux/fs.h usability... no
	checking linux/fs.h presence... no
	checking for linux/fs.h... no
	checking locale.h usability... yes
	checking locale.h presence... yes
	checking for locale.h... yes
	checking paths.h usability... yes
	checking paths.h presence... yes
	checking for paths.h... yes
	checking poll.h usability... yes
	checking poll.h presence... yes
	checking for poll.h... yes
	checking pwd.h usability... yes
	checking pwd.h presence... yes
	checking for pwd.h... yes
	checking regex.h usability... yes
	checking regex.h presence... yes
	checking for regex.h... yes
	checking signal.h usability... yes
	checking signal.h presence... yes
	checking for signal.h... yes
	checking stdarg.h usability... yes
	checking stdarg.h presence... yes
	checking for stdarg.h... yes
	checking for stdint.h... (cached) yes
	checking for stdlib.h... (cached) yes
	checking for string.h... (cached) yes
	checking sys/acl.h usability... yes
	checking sys/acl.h presence... yes
	checking for sys/acl.h... yes
	checking sys/extattr.h usability... no
	checking sys/extattr.h presence... no
	checking for sys/extattr.h... no
	checking sys/ioctl.h usability... yes
	checking sys/ioctl.h presence... yes
	checking for sys/ioctl.h... yes
	checking sys/mkdev.h usability... no
	checking sys/mkdev.h presence... no
	checking for sys/mkdev.h... no
	checking sys/param.h usability... yes
	checking sys/param.h presence... yes
	checking for sys/param.h... yes
	checking sys/poll.h usability... yes
	checking sys/poll.h presence... yes
	checking for sys/poll.h... yes
	checking sys/select.h usability... yes
	checking sys/select.h presence... yes
	checking for sys/select.h... yes
	checking sys/time.h usability... yes
	checking sys/time.h presence... yes
	checking for sys/time.h... yes
	checking sys/utime.h usability... no
	checking sys/utime.h presence... no
	checking for sys/utime.h... no
	checking time.h usability... yes
	checking time.h presence... yes
	checking for time.h... yes
	checking for unistd.h... (cached) yes
	checking utime.h usability... yes
	checking utime.h presence... yes
	checking for utime.h... yes
	checking wchar.h usability... yes
	checking wchar.h presence... yes
	checking for wchar.h... yes
	checking wctype.h usability... yes
	checking wctype.h presence... yes
	checking for wctype.h... yes
	checking windows.h usability... no
	checking windows.h presence... no
	checking for windows.h... no
	checking for clock_gettime in -lrt... no
	checking for clock_gettime... no
	checking sys/sysinfo.h usability... no
	checking sys/sysinfo.h presence... no
	checking for sys/sysinfo.h... no
	checking for sysinfo... no
	checking for struct sysinfo... no
	checking for struct sysinfo.totalram... no
	checking for struct sysinfo.mem_unit... no
	checking for sys/mount.h... yes
	checking for sys/statfs.h... no
	checking for sys/statvfs.h... yes
	checking for sys/vfs.h... no
	checking sys/sysctl.h usability... yes
	checking sys/sysctl.h presence... yes
	checking for sys/sysctl.h... yes
	checking for struct statfs.f_fstypename... yes
	checking for struct statfs.f_type... yes
	checking for struct statvfs.f_fstypename... no
	checking for struct statvfs.f_basetype... no
	checking linux/magic.h usability... no
	checking linux/magic.h presence... no
	checking for linux/magic.h... no
	checking zlib.h usability... yes
	checking zlib.h presence... yes
	checking for zlib.h... yes
	checking for inflate in -lz... yes
	checking openssl/rsa.h usability... yes
	checking openssl/rsa.h presence... yes
	checking for openssl/rsa.h... yes
	checking for RSA_private_encrypt in -lcrypto... yes
	checking bzlib.h usability... yes
	checking bzlib.h presence... yes
	checking for bzlib.h... yes
	checking for BZ2_bzDecompressInit in -lbz2... yes
	checking lzmadec.h usability... no
	checking lzmadec.h presence... no
	checking for lzmadec.h... no
	checking for lzmadec_decode in -llzmadec... no
	checking lzma.h usability... yes
	checking lzma.h presence... yes
	checking for lzma.h... yes
	checking for lzma_stream_decoder in -llzma... yes
	checking openssl/md5.h usability... yes
	checking openssl/md5.h presence... yes
	checking for openssl/md5.h... yes
	checking openssl/ripemd.h usability... yes
	checking openssl/ripemd.h presence... yes
	checking for openssl/ripemd.h... yes
	checking openssl/sha.h usability... yes
	checking openssl/sha.h presence... yes
	checking for openssl/sha.h... yes
	checking md5.h usability... no
	checking md5.h presence... no
	checking for md5.h... no
	checking ripemd.h usability... no
	checking ripemd.h presence... no
	checking for ripemd.h... no
	checking rmd160.h usability... no
	checking rmd160.h presence... no
	checking for rmd160.h... no
	checking sha.h usability... no
	checking sha.h presence... no
	checking for sha.h... no
	checking sha1.h usability... no
	checking sha1.h presence... no
	checking for sha1.h... no
	checking sha2.h usability... no
	checking sha2.h presence... no
	checking for sha2.h... no
	checking sha256.h usability... no
	checking sha256.h presence... no
	checking for sha256.h... no
	checking for library containing SHA1_Init... none required
	checking for MD5_Init... yes
	checking for RIPEMD160_Init... yes
	checking for SHA1_Init... yes
	checking for SHA256_Init... yes
	checking for SHA384_Init... yes
	checking for SHA512_Init... yes
	checking for an ANSI C-conforming const... yes
	checking for inline... inline
	checking for uid_t in sys/types.h... yes
	checking for mode_t... yes
	checking for off_t... yes
	checking for size_t... yes
	checking for id_t... yes
	checking for uintptr_t... yes
	checking for struct stat.st_birthtime... yes
	checking for struct stat.st_birthtimespec.tv_nsec... yes
	checking for struct stat.st_mtimespec.tv_nsec... yes
	checking for struct stat.st_mtim.tv_nsec... no
	checking for struct stat.st_mtime_n... no
	checking for struct stat.st_umtime... no
	checking for struct stat.st_mtime_usec... no
	checking for struct stat.st_blksize... yes
	checking for struct stat.st_flags... yes
	checking for uintmax_t... yes
	checking for unsigned long long... yes
	checking for unsigned long long int... yes
	checking for long long int... yes
	checking for intmax_t... yes
	checking for int64_t... yes
	checking for uintmax_t... (cached) yes
	checking for uint64_t... yes
	checking whether SIZE_MAX is declared... yes
	checking whether SSIZE_MAX is declared... no
	checking whether INT64_MAX is declared... yes
	checking whether INT64_MIN is declared... yes
	checking whether UINT64_MAX is declared... yes
	checking whether UINT32_MAX is declared... yes
	checking whether EFTYPE is declared... yes
	checking whether EILSEQ is declared... yes
	checking for wchar_t... yes
	checking size of wchar_t... 4
	checking whether time.h and sys/time.h may both be included... yes
	checking whether gcc needs -traditional... no
	checking whether sys/types.h defines makedev... yes
	checking for _LARGEFILE_SOURCE value needed for large files... no
	checking for working memcmp... yes
	checking whether lstat correctly handles trailing slash... no
	checking whether lstat accepts an empty string... no
	checking whether stat accepts an empty string... no
	checking whether strerror_r is declared... yes
	checking for strerror_r... yes
	checking whether strerror_r returns char *... no
	checking for strftime... yes
	checking for vprintf... yes
	checking for _doprnt... no
	checking for chflags... yes
	checking for chown... yes
	checking for chroot... yes
	checking for fchdir... yes
	checking for fchflags... yes
	checking for fchmod... yes
	checking for fchown... yes
	checking for fcntl... yes
	checking for fork... yes
	checking for fstat... yes
	checking for ftruncate... yes
	checking for futimes... yes
	checking for geteuid... yes
	checking for getpid... yes
	checking for lchflags... yes
	checking for lchmod... yes
	checking for lchown... yes
	checking for lutimes... yes
	checking for memmove... yes
	checking for memset... yes
	checking for mkdir... yes
	checking for mkfifo... yes
	checking for mknod... yes
	checking for nl_langinfo... yes
	checking for pipe... yes
	checking for poll... yes
	checking for readlink... yes
	checking for select... yes
	checking for setenv... yes
	checking for setlocale... yes
	checking for strchr... yes
	checking for strdup... yes
	checking for strerror... yes
	checking for strrchr... yes
	checking for timegm... yes
	checking for tzset... yes
	checking for unsetenv... yes
	checking for utime... yes
	checking for utimes... yes
	checking for vfork... yes
	checking for wcrtomb... yes
	checking for wcscpy... yes
	checking for wcslen... yes
	checking for wctomb... yes
	checking for wmemcmp... yes
	checking for wmemcpy... yes
	checking for lockf... yes
	checking for posix_memalign... yes
	checking for qsort_r... yes
	checking for mmap... yes
	checking whether D_MD_ORDER is declared... yes
	checking for working POSIX fnmatch... yes
	checking whether FNM_LEADING_DIR is declared... yes
	checking for struct dirent.d_namlen... yes
	checking for attr/xattr.h... (cached) no
	checking sys/xattr.h usability... yes
	checking sys/xattr.h presence... yes
	checking for sys/xattr.h... yes
	checking for setxattr in -lattr... no
	checking for extattr_get_file... no
	checking for extattr_list_file... no
	checking for extattr_set_fd... no
	checking for extattr_set_file... no
	checking for fsetxattr... yes
	checking for getxattr... yes
	checking for lgetxattr... no
	checking for listxattr... yes
	checking for llistxattr... no
	checking for lsetxattr... no
	checking for sys/acl.h... (cached) yes
	checking for acl_get_file in -lacl... no
	checking for acl_create_entry... yes
	checking for acl_init... yes
	checking for acl_set_fd... yes
	checking for acl_set_fd_np... yes
	checking for acl_set_file... yes
	checking for acl_permset_t... yes
	checking for acl_get_perm_np... yes
	checking for acl_get_perm... no
	checking whether ACL_USER is declared... no
	checking for special C compiler options needed for large files... no
	checking for _FILE_OFFSET_BITS value needed for large files... no
	checking whether optarg is declared... yes
	checking whether optind is declared... yes
	checking whether to install bash completion... no
	checking that generated files are newer than configure... done
	configure: creating ./config.status
	config.status: creating Makefile
	config.status: creating config.h
	config.status: config.h is unchanged
	config.status: executing depfiles commands

**Comment by cperciva** [comment]
Fixed in 00bf9764,
