### ISSUE TITLE
escaping bug/typo in tarsnap(1) manpage

### ISSUE THREAD

**Issue by WesleyAC** [Tarsnap/tarsnap#460]
I noticed today that `man tarsnap` reads:

       Upon receipt of the SIGQUIT signal or ua Q, or if the bandwidth limit
       specified via a --maxbw option is reached, tarsnap will interrupt the
       creation of an archive and truncate it at the current position.

From looking at the source, it seems like this is an escaping bug, and `ua Q` should read `^Q`. I see this in my local copy and also on https://www.tarsnap.com/man-tarsnap.1.html.

**Comment by gperciva** [comment]
Thanks for the report!  I believe that this was fixed in 1ac0b67b264993b0844b284c5830131d791c0134, but that was after the latest official release (version 1.0.39).
