### ISSUE TITLE
Feature Request: SIGINFO Support

### ISSUE THREAD

**Issue by lattera** [Tarsnap/tarsnap#49]
For obvious reasons. SIGINFO support would be extremely nice.

**Comment by cperciva** [comment]
Err... yes, it is.  And it's already there. ;-)

**Comment by lattera** [comment]
Ah, so it is. The first time I hit ^T, only the system SIGINFO handler gave output, not tarsnap. Maybe I just needed to be more patient. Closing bug. Ignore this blonde moment. ;)

**Comment by cperciva** [comment]
It's possible that you hit ^T before tarsnap's siginfo handler was installed.  Or maybe you just didn't wait long enough for it to check if the signal had been received (standard idiom, the signal handlers sets a flag which gets polled from the rest of the code).
