### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jturner** [Tarsnap/tarsnap#512]
What are the odds of a new release? OpenBSD will need this recent change (https://github.com/Tarsnap/tarsnap/commit/65fde80353b1bc53651fa8507ab32336b3d838ea) and we aren't allowed to have patches against tarsnap in our ports tree or are users can't use the official service per the ToC.

Thanks.

**Comment by cperciva** [comment]
We're planning on doing a release soon.

In the mean time, I hereby give you / OpenBSD / etc permission to distribute Tarsnap with that patch. ;-)

**Comment by jturner** [comment]
Thank you! We have included a patch in the meantime and look forward to the new release!
