### ISSUE TITLE
workaround for libc/kernel disagreement about whether lchmod exists

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/tarsnap#558]
We need

https://github.com/libarchive/libarchive/commit/51d3acf90c259be3224e22de934b02df3c71f20c
https://github.com/libarchive/libarchive/commit/5ad9ecddb52edd096423d9f43bb5d228f2e07f57

merged to work around a problem where libc defines lchmod but the kernel doesn't support it.  Oh, the joys of operating systems where the kernel and libc are developed independently...

**Comment by gperciva** [comment]
We merged these in #559.
