### ISSUE TITLE
Release under a "free" license

### ISSUE THREAD

**Issue by tomfitzhenry** [Tarsnap/tarsnap#66]
I'd like Tarsnap to be distributed by Debian/Ubuntu for a few reasons:
* it's useful for other packages to depend on Tarsnap (e.g. an application's own backup scripts, which are packaged)
* compiling the package is more faff than `apt-get install tarsnap`
* I trust packages distributed by the Debian project moreso than those in unofficial apt repositories (of which there are numerous for distributing Tarsnap)

I was about to raise a [Debian Request For Package](https://wiki.debian.org/RFP) for Tarsnap, but I noticed that [Tarsnap's license](https://github.com/Tarsnap/tarsnap/blob/22e3af45667d48281c19e9ad1e091fb5b7ef7065/COPYING) includes:

> Redistribution and use in source and binary forms, without modification,
is permitted for the sole purpose of using the "tarsnap" backup service
provided by Tarsnap Backup Inc.

As such, it is not DFSG (nor FSF's definition of "free"), and cannot be distributed with Debian.

Please could this be reconsidered, and ideally released under a DFSG license, e.g. a BSD license.

**Comment by cperciva** [comment]
I'd love to see Tarsnap packages in debian, but I can't change the license.  Tarsnap is commercial software, not open source software, and changing the license would make it too easy for the code to be repurposed in ways which result in me not getting paid (e.g., setting up competing tarsnap-compatible services).  I BSD-license code whenever I can, but the commercial reality just wouldn't work here.

Could tarsnap go into the debian non-free archive?

**Comment by tomfitzhenry** [comment]
If I was in your shoes, I doubt I'd make it freely available, so I can't complain too loudly. :)

I'd somehow forgotten about Debian's non-free archive. Thanks for the suggestion, I've raised an issue there: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799214

**Comment by cperciva** [comment]
Thank you for understanding. :-)

In case it helps with the RFP, there are debian packaging bits in the tarsnap source tree already: https://github.com/Tarsnap/tarsnap/tree/master/pkg/debian

These were contributed to tarsnap 6 years ago and haven't been changed much since then beyond me updating the changelog; so I'm sure it could benefit from an experienced Debian developer looking it over, but it might be a useful starting point at least.

**Comment by etug80** [comment]
@cperciva 

> Tarsnap is commercial software, not open source software, and changing the license would make it too easy for the code to be repurposed in ways which result in me not getting paid (e.g., setting up competing tarsnap-compatible services).

I think what you need in this case is CC BY-NC-SA 4.0 license. Here, https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by gperciva** [comment]
@etug80: thanks for your interest, but CC BY-NS-SA 4.0 is not suitable for tarsnap, since @cperciva already said that we do not want people to modify the code.

**Comment by gperciva** [comment]
@etug80: we do publish some code related to tarsnap under the BSD license:

* [scrypt, for secure key derivation](https://www.tarsnap.com/scrypt.html)
* [spiped, the secure pipe daemon](https://www.tarsnap.com/spiped.html)
* [kivaloo, a data store for 255 bytes](https://www.tarsnap.com/kivaloo.html)
* [tarsnap-gui, still under heavy development](https://github.com/Tarsnap/tarsnap-gui)

More information about our open-source work is available on
https://www.tarsnap.com/open-source.html
