### ISSUE TITLE
--keep-going option?

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/tarsnap#77]
When running `tarsnap --print-stats` or `tarsnap -d`, multiple `-f` options can be specified.  It might be a good idea to have a `--keep-going` option which makes tarsnap continue if one of the archives specified does not exist.

Use case: Trying to create daily archives, but sometimes the archives don't get created (e.g., laptop + cron job).  Want to delete a set of old archives without worrying about not deleting the ones which aren't there in the first place.

Another use case: Deleting a list of archives, network glitches in the middle.  Want to restart the deletes and skip the ones which were already deleted.

**Comment by gperciva** [comment]
This has been merged, and will appear in 1.0.37.
