### ISSUE TITLE
tarsnap --print-key-id

### ISSUE THREAD

**Issue by cperciva** [Tarsnap/tarsnap#87]
Read a key file and print the machine ID #.  Will be undocumented; this is a private interface for the GUI to use.

**Comment by gperciva** [comment]
Might I register a slight protest against "will be undocumented"?  Is there any foreseeable harm in documenting it with something like "This is unlikely to be useful when tarsnap is being invoked directly from the command line." (as we did for `--creationtime`) ?

**Comment by gperciva** [comment]
Another idea: in addition to making it public, how about adding a separate `--print-key-permissions` (or `authorization` which would print whether that key had READ, WRITE, DELETE, NUKE permissions.  This arose on the mailing list in 2012:  http://mail.tarsnap.com/tarsnap-users/msg00542.html

**Comment by gperciva** [comment]
This was added (with documentation) in #87.
