### ISSUE TITLE
build failing on head

### ISSUE THREAD

**Issue by jungle-boogie** [Tarsnap/tarsnap#88]
Occasionally I build tarsnap from the github but I had this failure this morning:

keygen/tarsnap_keygen-keygen.o `test -f 'keygen/keygen.c' || echo './'`keygen/keygen.c
mv -f keygen/.deps/tarsnap_keygen-keygen.Tpo keygen/.deps/tarsnap_keygen-keygen.Po
cc -I./libarchive                -I./tar                         -I./lib/crypto          -I./lib/datastruct              -I./lib/keyfile                 -I./lib/netpacket               -I./lib/netproto                -I./lib/network       -I./lib/util             -I./libcperciva/crypto  -I./libcperciva/util    -DUSERAGENT=\"tarsnap-keygen-1.0.36-head\" -g -O2    -o tarsnap-keygen keygen/tarsnap_keygen-keygen.o -lcrypto lib/libtarsnap.a lib/libtarsnap_aesni.a  lib/libtarsnap_sse2.a -llzma -lbz2 -lcrypto -lz -lrt
keygen/tarsnap_keygen-keygen.o: In function `main':
/usr/home/jungle/bin/tarsnap/keygen/keygen.c:174: undefined reference to `keygen_network_register'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[1]: stopped in /usr/home/jungle/bin/tarsnap
*** Error code 1

Stop.
make: stopped in /usr/home/jungle/bin/tarsnap

This is after a simple `./configure` and even a `make clean`. 

Is there something I'm doing wrong?

Thanks!

**Comment by cperciva** [comment]
Did you run `autoreconf -i` again?  If you had old autotools files in your tree that would explain why the new file didn't get linked in.

**Comment by jungle-boogie** [comment]
Hi @cperciva,

thanks! that fixed it and I'll try that next time a fail happens.
